user_token: вставьте_ваш_токен_вместо_этой_строки

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
database:
  host: 0.0.0.0
  port: 5432
  user: kts_user
  password: kts_pass
  database: kts
bot:
  token: vk1.a.WzNXoOtvEg5IjCjg4vIiPTlziBdd4RlY_9nBHalzb6f5Wp_Mo3J0Tu57zgL8ae-UCG8q0VnwY0Lilng3UfemEy1DbIiL1dbgs7e7GRRE6ZfY0dl9VZQhPoaoE5k4srxXbFv1-jm9sC7QQNUtX3MNanL288iqiq-y6kzyo2vrKJeUAVJ7rTTFOTg8xqbJGsryrFssXS-QAcLaF75XORCW2w
  group_id: 218949683


